# These are supported funding model platforms

github: "Pr0methean" # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
tidelift: "maven/io.github.pr0methean.betterrandom:BetterRandom-Java7"
tidelift: "maven/io.github.pr0methean.betterrandom:BetterRandom"
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom: ["https://www.buymeacoffee.com/IMypBXw", "https://www.canwork.io/profile/chris-hennick-8"]