if: tag IS blank
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/Library/Developer/Xcode"
dist: trusty
serialGroup: edge
git:
  depth: 10
  quiet: true
  submodules: true
stages:
- unit tests
- long tests
jobs:
  include:
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=unit-tests ANDROID=1 JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode6.4
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode7.3
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode8.3
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode9.3
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode9.4
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=unit-tests JAVA8=true LIMITED_CRYPTO=true
    stage: unit tests
    sudo: required
  - language: java
    os: linux
    jdk: openjdk9
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: openjdk10
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: openjdk11
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk11
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=mutation
    stage: long tests
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=benchmark ANDROID=1 JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode6.4
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode7.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode8.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode9.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode9.4
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk9
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk10
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk11
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk11
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=AesCounterRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=CellularAutomatonRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=Cmwc4096Random
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=MersenneTwisterRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=Pcg64Random
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=XorShiftRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=adapter.SingleThreadSplittableRandomAdapter
    stage: long tests
  fast_finish: true
addons:
  apt:
    packages:
    - tor
    - dieharder
script:
- ifconfig | grep inet
- "./remove_unlimited_crypto.sh"
- "./${OP}.sh"
env:
  global:
  - secure: mjRT9tToZDB7ZIY2TglFIyKvHs6+Rt86gUMSCagmk7sur00/XQnY/XCuPNhIyr2wow0e8QrS+peOEz+SyZLQTnoMHnpq8DCoUrrGr2XZA0aOFJVvVG3jgDZeoC0nKpQXurai7qjO+FppQPcjP5slbHz8Fas56CPUdMHo1aXdoEdmCdh9/+yjeZ/LxvDNYTPQ/jY+v55EUbDWoTUu3k3kDg6mDPpavtUCA1sBocO8i4gsu/Oh+0/j8c2uPr9OTa9ew7jPgMsGH9J7ZlsOhh7xj0TmYTDapmBINRnsWmHy6iN0o++xusGh5frVHOeE9YxKzSVpW4ZKOgAoeMIy6UeQoECmLNXECK2XoRiNMkji9aZbxajbD2Wu0Oy7rRP8lOxl71jgd4mvVV+qBMVmN/73LHzYwkVQuxbHtMbvgOVdg81f0oD1T5tOlR3B1fGBWGX44NTUg8unZNJ1vhx9ms4shVXYP682DBeqlY8/RiqUsP+2XqexQR0FjQUZQqu9iSUKUSrBoCjdEH43cyFZjVeHGwsn0MHOJDWwjkISKVPwWfj8etVm8BoVcQETF0jyBTIjCiYFKxN4i6GfY1JIy/AqCSF0jsS6UKfy/m6kHliScTde5n1tIPcRyx55vshotz7jXDrPgU7jcuo8RUyL+UrBirFgNgY3tUkWLg4PUu0CVyY=
  - secure: F4hmUJY5bSA8ZuRhN8+zt24ZOGyAu+YvWiWipxPf/VnoAnSUx5XFupVHE5ngFI2bKmh5UafYfHeWigqh19tP8YRFXU+IirvS4/WOmwTrVmTNiOw0qieU+y6CDL1CQTpBNmAL8ZSsm5BhFlLEk7tO+At3jAIsrMbWAAXmp1fvQSOwKGUUNT51evrlh7ewYFyQurJZUVJgecZqp2olVc2tqjXHDNoOdOzkvKXFV5HA8nEnRiTU1c1U4OffOzV/ZrqIuqNwLdGOBRjPY9om2dYB7DCfbfM+yDnb6p5xdnigX78BeADDdG44/3DH89siM6T7KlFhJzYmahFi58NZ+yXCHgdvi4uOHLQj6qLBXsAoINcLE6wSJhY0ymVMLgsiJA+2r6c0RoF5Ro8MvIH8Ceta22WJaTXtT71cqcHuznD4CBUfDm5LOMDmH6m2drBs7wkWEwpLlDTXhnBTNu9bPejUhvkCht8ndmmLq1UoswvhYiS2NgsAqov5LBqspAJ31fu9FB+jHWrzglnWjX/tZ2IF6jmCZjatnHsdQQ32WjYpR8Gt9v7/zRUymbO8G6twROcyMC2sgSKqXkMnxB6D48QvvVD77IpaPAEFoRXI+ktT5YZVVXGUzDhvwcA2JRFaUJ9SDAapYf5tcwK6r80O+ZJ5ul6P/81cOG8WqbY2gBwrjjs=
  - secure: "vx3JhbeNhTipF8hBDujinTeiAQTxCK6HDrT1LG7bipLgs9gaAKY5a7+dWJzHTAA6AtEC1gR0JUG3vuDGs1eF37qb+ZO1mx0GAy18VlVlHl2qEhC0WoQeoTSVsmFmZlUxfviLcGfjtvgwN+683jDULmx1g0uf62iPitEL6KhfWuwXoqf9JBnjhxID9aVWWS9bVpyYNPMXofaZfl0o/scaATzsCHMtA7XQz22mPbMZrI8GBSBjPY61jIgls1yFZaCwO6aOKmo44CPMBDVPWluU1NIn0xUwV6p5yxbKVQaFfMHdLjNzO1RcQmZlWSwrQYEmfFZvMgIHzecx4hQz+GrLc9VCiNuR2OTnBnHTqtUUBlnV/Y1IoCukTrd8MR60Yr3pOiotw2OwlyH9gkBjLR96QZXNWnIN+QPhqWi5qss9nut56YsZ18Hr14jrMFlADl/6RBCESgIWT0Vz4dY+Gpn9zfJT4TOf+lBPCqdqOYqR+tt5nam8zpiaDCzKoQQKJ0F0DQEJaosttVf/LN1zQzGwobdpBqh9gvJ2Fnm6wzP8V+5A7t5ZCJ5QhGuNsQGrvZebHH57I37p9lfdm1sjfIzVWF3S/a0Kltq+BF6wARNvx/vpnF7E1IgqlIBRijHO5gltSyOsx4zcjn1dKkFO/MwqTexz5gTpF3Y391lPJNtEIBU="