sudo: required
dist: trusty
group: edge
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
env:
  - MODE=coverage
  - MODE=test-proguard
matrix:
  allow_failures:
    - jdk: oraclejdk9 # Currently doesn't set JAVA_HOME correctly for Maven
script:
  # Test AesCounterRandom with limited-strength crypto on Oracle
  - sudo mv -f travis-resources/local_policy.jar $JAVA_HOME/jre/lib/security/local_policy.jar
  - sudo mv -f travis-resources/US_export_policy.jar $JAVA_HOME/jre/lib/security/US_export_policy.jar
  - ./${MODE}.sh