sudo: required
dist: trusty
group: edge
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
matrix:
  allow_failures:
    - jdk: oraclejdk9 # Currently doesn't set JAVA_HOME correctly for Maven
script:
  - mkdir /home/travis/javalog
  - mvn test
