os:
  - linux
  - osx
sudo: required
dist: trusty
group: edge
language:
  - java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
env:
  - OP=unit-tests
  - OP=benchmark
matrix:
  include:
    - language: android
      os: linux
      jdk: openjdk8
      env: OP=unit-tests ANDROID=1
    - language: android
      os: linux
      jdk: openjdk8
      env: OP=benchmark ANDROID=1
  allow_failures:
    - jdk: oraclejdk9 # Currently doesn't set JAVA_HOME correctly for Maven
  fast_finish: true
script:
  # Test AesCounterRandom with limited-strength crypto on Oracle
  - sudo mv -f travis-resources/local_policy.jar $JAVA_HOME/jre/lib/security/local_policy.jar
  - sudo mv -f travis-resources/US_export_policy.jar $JAVA_HOME/jre/lib/security/US_export_policy.jar
  - ./${OP}.sh