sudo: required
dist: trusty
group: edge
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk8
matrix:
  allow_failures:
    - jdk: oraclejdk9 # Currently doesn't set JAVA_HOME correctly for Maven
script:
  # Test AesCounterRandom with limited-strength crypto on Oracle
  - rm $JAVA_HOME/jre/lib/security/local_policy.jar
  - rm $JAVA_HOME/jre/lib/security/US_export_policy.jar

  - mvn jacoco:prepare-agent test jacoco:report coveralls:report
