sudo: required
dist: trusty
group: edge
git:
  submodules: false
matrix:
  include:
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=unit-tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=unit-tests
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode9
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode8.3
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode8.2
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode8.1
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode8
    env: OP=unit-tests
  - language: java
    os: osx
    osx_image: xcode7.3
    env: OP=unit-tests
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=unit-tests ANDROID=1
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=benchmark
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=benchmark
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=benchmark
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=benchmark ANDROID=1
  - language: java
    os: osx
    osx_image: xcode9
    env: OP=benchmark
  - language: java
    os: osx
    osx_image: xcode8.3
    env: OP=benchmark
  - language: java
    os: osx
    osx_image: xcode8.2
    env: OP=benchmark
  - language: java
    os: osx
    osx_image: xcode8.1
    env: OP=benchmark
  - language: java
    os: osx
    osx_image: xcode8
    env: OP=benchmark
  - language: java
    os: osx
    osx_image: xcode7.3
    env: OP=benchmark
  allow_failures:
  - jdk: oraclejdk9
  - language: android
  fast_finish: true
script:
- "./remove_unlimited_crypto.sh"
- "./${OP}.sh"
env:
  global:
  - secure: p6BU8Afyx81w+BwfgkjXgAC/OD6RDWQCEOusw3FSGrt0OSqmMPG3f617ndMWrTPXLekB6y1ZmaLKUSwlbG82oy961wg1rjb7KhfU39OSqzIvzynziRbzFftLX8rMH0dX8nnUc3yrCKxPhrJjnGjU41BlzMOug/i01CVn+PqUBqlSZI8Cqq6YxToGh4CX45TyHJpmx58x6MQ5LRfV3EUWaB83XBSaO2ih/tCRfqO+ryF7eav4daojtJbheONiPQ/ZfZV9TcPHftB6oYbWoGMBJ9YyD1jA4LHWondT+kkSPY2A0gOeTLFd0Ktj9suKS6qXY+QIhuStu8Ew64VOKDdOlLW804w1a438D4qf1Hr64r1lElTRhHoE0efL1vydSVby5gUJLqpru2RsNu29Ky0EovIx6i05d32xtq9kc+BNEl/SYBuUewolB9VbAmsvHGIgQG+3ZchDjcVAz4RAsVyKL1jNdzt2ZqBBlNggqcy2guCfk40IErBhP0fxxuCZy7l0NmjnhYSjaIR8AJ9525uMcbCNLlem1uUOYNpFT6O9I1U27F8Dh7I2qShlPh31UJswV3ASPqlWiGZ9HIsjf7c2OLKOke7RBcyYNn0lQ42nanMmlWhnGoQgzlYtRDY1rzbCcfz6r/xkr63QIEjVVfTjKP1fjnZmbdxsgs779BbCerY=
  - secure: kIjDcKkt6ggi1yS2g5eFI/rZ0mHZF3iQXlQTEqe/sk2pK3zvPoCjYEUZs5b7gxrb1jdsMjavf+WA0CPOtJb6KuU6GkwcFdmXlfZs0LrN5taV0TfLn+k27YvOhXpfFk2VwPaBVUYbMU/MHERKjpVu52uJS+KCaCXKmdpK8B5PVcxBIvOViufRi8ZGAZBrBaqRHvZTX0nt0KL2eULoKLhPxsuUC6fH3cJHGq1lphvPxA2SwVJVGg4NvBo3RVOu5L3QzD2eWfVQpjmBjQ7rgaxfEPqIHNZ9sThoWCNHUN+0TyFuSCleGjS5D8hHjy3bIGIcWyetxUZH3WUqDpYA9FjfuFzm978FVLDrYrdSgrDrIXu+HT7IoNNfKYC0HW2XbIuV4+exkkPRJYVrSd08HLSItqnB1yXAXZ58Z1mnCvX+ao4L3LmOsRixpw/u1bmnivZmNOA+207hAFyAROqFAaPgVc+skcpX4qcINFuL1eGv+i2cvOu489g4gqgM+7BvA/pf5cA/TsDGLDndVtmNct8O6oLK13/0UQxBP03FaTHH7BOcO5404BFZrw78X4QlteMIcI1MaDEgWoToujvA8X1XsyxUw+/iJ/AFRorF4tcOL+E/3CRSPigMWE6l1sy2Mhy+I+LD7mb3DwjiAzADGUNGXOFGvKAJLMXbeAdJhx2ul5A=
