if: tag IS blank
cache:
  directories:
  - $HOME/.m2
  - $HOME/Library/Developer/Xcode
dist: trusty
serialGroup: edge
git:
  depth: 10
  quiet: true
  submodules: true # Travis FIXME: Should be overridable per job
stages:
- unit tests
- long tests
jobs:
  include:
  # Android-SDK unit test
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=unit-tests ANDROID=1 JAVA8=true
    stage: unit tests
  # OSX unit tests
  - language: java
    os: osx
    osx_image: xcode6.4 # JDK 1.8.0_45-b14, OSX 10.10
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode7.3 # JDK 1.8.0_92-b14, OSX 10.11
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode8.3 # JDK 1.8.0_112-b16, OSX 10.12
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode9.3 # JDK 1.8.0_112-b16, OSX 10.13
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: osx
    osx_image: xcode9.4 # JDK 10.0.1, OSX 10.13
    env: OP=unit-tests
    stage: unit tests
  # Linux unit tests
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=unit-tests JAVA8=true
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=unit-tests JAVA8=true LIMITED_CRYPTO=true
    stage: unit tests
    sudo: required
  - language: java
    os: linux
    jdk: openjdk9
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: openjdk10
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: openjdk11
    env: OP=unit-tests
    stage: unit tests
  - language: java
    os: linux
    jdk: oraclejdk11
    env: OP=unit-tests
    stage: unit tests
# Uncomment once OpenJDK 12 enters EA
#  - language: java
#    os: linux
#    jdk: openjdk-ea
#    env: OP=unit-tests
#    stage: unit tests
  # Mutation test
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=mutation
    stage: long tests
  # Android-SDK benchmark
  - language: android
    os: linux
    jdk: openjdk8
    env: OP=benchmark ANDROID=1 JAVA8=true
    stage: long tests
  # OSX benchmarks
  - language: java
    os: osx
    osx_image: xcode6.4
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode7.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode8.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode9.3
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: osx
    osx_image: xcode9.4
    env: OP=benchmark
    stage: long tests
  # Linux benchmarks
  - language: java
    os: linux
    jdk: openjdk8
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk8
    env: OP=benchmark JAVA8=true
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk9
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk9
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk10
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=benchmark
    stage: long tests
# Uncomment once OpenJDK 12 enters EA
#  - language: java
#    os: linux
#    jdk: openjdk-ea
#    env: OP=benchmark
#    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk11
    env: OP=benchmark
    stage: long tests
  - language: java
    os: linux
    jdk: openjdk11
    env: OP=benchmark
    stage: long tests
  # Dieharder
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=AesCounterRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=CellularAutomatonRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=Cmwc4096Random
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=MersenneTwisterRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=Pcg64Random
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=XorShiftRandom
    stage: long tests
  - language: java
    os: linux
    jdk: oraclejdk10
    env: OP=dieharder CLASS=adapter.SingleThreadSplittableRandomAdapter
    stage: long tests
  fast_finish: true
addons:
  apt:
    packages:
      - tor
      - dieharder
script:
- ifconfig | grep inet
- "./remove_unlimited_crypto.sh"
- "./${OP}.sh"
env:
  global:
  - secure: "q7fcoiQBIB+6LqQuP7l41aZOk+j9VpW4dBUER+ALHXc9p9ZPIri5tj7jZDlh993zXdlGnlJ9FHwinZUiXaMjMnRoHX0EB+7x703URNugfQvSDOTDzqo6KlXfJuiGvyREMSCwejINIwyckCW35wuf9mWngQYasLvQd8pdLlrIFa81iIcEu1GLi8SZM2f3dCORATdEcZWoav8FYVodZ8ZncLJYeMvn2Phg/9gwWK4u/bbxcGf52d4+oMj5aKdgeYiWxIysQ3Soq6b/DPWVenlsb2Rbu+howmwBJEv1XH69ZTp3lwWadAQkzRRGbsIENqFXakEmepySi6Xfi5X7GYMQNKVQsUoMfeFVC1ctuUIqmAq1rvq/HD+rl8BmzwjCp4aVDTyRzKuRD6L8IO3fQM8PY8N0gAnXQ9gx1Sswejo4oFoj/fFWFIZfM5VRj/27GLKKM/F7jgtQW4y8q1Q1L7On0htnQzm3B7JuZ6iuSA0XLbNpJxGcPCTkqCeBWXqo5Vk1kJxCm48o8sZMiJ0nm1V8cQrVd/uaExEb4NBFFYY/xshsqJpfrvYT9R5gbRr4uyTz9h7d3XgQoAJEMPJFkDZGCbZNwYaKAjlvzamAFnuwBlFmNhvsqLDZctBauLsWOFVjVwNA/EuysYOcEiJb311h24Vu45hsOG/oYlLFrbZngqA="
  - secure: M/ffKiA1inknBVmlzXg9VqsRJihfZyzn4oJ/JF1y4k7du/FSe1q/wpyYWrPN/qotpEfO+UZKh1UHbfMQab7DJ3wsQyvwLp9LD8hildKpmktHAcBWZNMf+MYn4NsykLitZVwve/kg2ptrvDqVN7nNsIzUVDCAxhVP6rPv5wGeaTVPtjJ6GhgSIywbBfoW344elE5KE4QzECmrnt/02Pt9A8FfJjVZ+/boaj8/0VMLgxglpMVCww57UsUdwRfwyHSusv4mcFCHQtzXyecZ6Yxw1en5UbO+I68cTq4a27JO1jnjWNX6uIT8wWpAurujd4HvfmJeITRnan01+3DBMTkAH08QffGMjPTYM4P2XcCP4uA5+XeerOiu/yxaTCq/cElbrLWbKllk2VgB+OBl2baV6jKE/fgSisofTYt0I2Ic2CiuSpXmTicTyXYGv3cHynvw5FlpgBKjw70eZh8F8GYHKmk1RprV3n7gSmpxG69EuGv7yIG1EVJOXSNU/WkrzwtQYi52LZ9C8itmczZ3oasiPI2sUvuZbJs5+UrVRW8Nbm7/3hpE5qaxZj7UgkJovd6PS2LUZC5xBvJb0qK0wVp/iLcPELd7/Sp7ewE+URsklfUqXGASt11cuMxI0kGi5ghwoG72vLqtmFkUzImFOjhJIuvSZJSn+nQi7gMGj4nEPYQ=
  - secure: mjRT9tToZDB7ZIY2TglFIyKvHs6+Rt86gUMSCagmk7sur00/XQnY/XCuPNhIyr2wow0e8QrS+peOEz+SyZLQTnoMHnpq8DCoUrrGr2XZA0aOFJVvVG3jgDZeoC0nKpQXurai7qjO+FppQPcjP5slbHz8Fas56CPUdMHo1aXdoEdmCdh9/+yjeZ/LxvDNYTPQ/jY+v55EUbDWoTUu3k3kDg6mDPpavtUCA1sBocO8i4gsu/Oh+0/j8c2uPr9OTa9ew7jPgMsGH9J7ZlsOhh7xj0TmYTDapmBINRnsWmHy6iN0o++xusGh5frVHOeE9YxKzSVpW4ZKOgAoeMIy6UeQoECmLNXECK2XoRiNMkji9aZbxajbD2Wu0Oy7rRP8lOxl71jgd4mvVV+qBMVmN/73LHzYwkVQuxbHtMbvgOVdg81f0oD1T5tOlR3B1fGBWGX44NTUg8unZNJ1vhx9ms4shVXYP682DBeqlY8/RiqUsP+2XqexQR0FjQUZQqu9iSUKUSrBoCjdEH43cyFZjVeHGwsn0MHOJDWwjkISKVPwWfj8etVm8BoVcQETF0jyBTIjCiYFKxN4i6GfY1JIy/AqCSF0jsS6UKfy/m6kHliScTde5n1tIPcRyx55vshotz7jXDrPgU7jcuo8RUyL+UrBirFgNgY3tUkWLg4PUu0CVyY=
