# http://www.appveyor.com/docs/appveyor-yml
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  matrix:
    - OP: unit-tests
      RUNNER: MinGW\msys\1.0
    - OP: benchmark
      RUNNER: MinGW\msys\1.0
    - OP: unit-tests
      RUNNER: cygwin64
    - OP: benchmark
      RUNNER: cygwin64
install:
  # Log versions for debugging
  - java -version
  - mvn --version
build_script: # dummy, as shell scripts both build and test
  - echo
test_script:
  - c:\%RUNNER%\bin\sh ./%OP%.sh
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
matrix:
  fast_finish: true