# http://www.appveyor.com/docs/appveyor-yml
init:
  # 32-bit Cygwin causes conflicts
  - rmdir c:\cygwin /s /q
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  matrix:
   - COMMAND: powershell .\unit-tests.ps1
   - COMMAND: c:\MinGW\msys\1.0\bin\sh .\unit-tests.sh
   - COMMAND: c:\cygwin64\bin\sh .\unit-tests.sh
   - COMMAND: powershell .\benchmark.ps1
   - COMMAND: c:\MinGW\msys\1.0\bin\sh .\benchmark.sh
   - COMMAND: c:\cygwin64\bin\sh .\benchmark.sh
  access_token:
    secure: UrMOuu5SzFyDvmnIwDu4EJol6YwyLJJ3yAAvA8URK7x8cmssL4106Wr8MmS01GGL
  random_dot_org_key:
    secure: SdVpsz4/hDKlxV/jEehj9kEUmbIrrq5yvDOWYrHyxN+WE1z8CNeeTnv8BuQ6XsnN
  APPVEYOR_RDP_PASSWORD:
    secure: prROYXFdZ1WD7poOqYxXuRIF6KkKWjAWAWZX5PaHABM=
install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  # Log versions for debugging
  - java -version
  - mvn --version
build_script:
  # shell scripts both build and test, so all we need to do here is set the character encoding
  - chcp 65001
test_script:
  - '%COMMAND%'
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
matrix:
  fast_finish: true
  allow_failures:
    - ALLOW_FAILURE: true
