variables:
  openjdk11linux: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_9.tar.gz'
  openjdk10linux: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2%2B13.tar.gz'
  openjdk09linux: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz'
  openjdk08linux: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz'
  openjdk11mac: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_mac_hotspot_11.0.2_9.tar.gz'
  openjdk10mac: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Mac_jdk-10.0.2%2B13.tar.gz'
  openjdk09mac: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_mac_hotspot_9_181.tar.gz'
  openjdk08mac: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz'
  openjdk11win: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.2_9.zip'
  openjdk10win: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Win_jdk-10.0.2%2B13.zip'
  openjdk09win: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_windows_hotspot_9.0.4_11.zip'
  openjdk08win: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip'
  openjnine11linux: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz'
  openjnine11mac: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_mac_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz'
  openjnine11win: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_windows_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.zip'
#  openjnine10linux: 'https://github.com/AdoptOpenJDK/openjdk10-openj9-releases/releases/download/jdk-10.0.2%2B13_openj9-0.9.0/OpenJDK10-OPENJ9_x64_Linux_jdk-10.0.2.13_openj9-0.9.0.tar.gz'
#  openjnine09linux: 'https://github.com/AdoptOpenJDK/openjdk9-openj9-releases/releases/download/jdk-9.0.4%2B12_openj9-0.9.0/OpenJDK9-OPENJ9_x64_Linux_jdk-9.0.4.12_openj9-0.9.0.tar.gz'
trigger:
  branches:
    include:
      #    - master
      #    - java7
      - azurePipeline201903
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
#pr:
#  branches:
#    include:
#    - master
#    - java7
#  paths:
#    exclude:
#    - README.md
#    - CHANGELOG.md
jobs:
  - job: UnitMac
    variables:
      JAVA_HOME: jdk
    strategy:
      matrix:
        OpenJdk10Mac:
          JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home'
          coverageName: OpenJdk10Mac
        OpenJdk11Mac:
          JAVA_HOME: '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'
          coverageName: OpenJdk11Mac
    pool:
      vmImage: 'macOs-10.13'
    steps:
      - script: ./unit-tests.sh
        displayName: Build & Test
      - template: etc/azureTemplate/publishCoverage.yml
  - job: AllUnitTests # empty job used in dependsOn for DRY reasons
    displayName: All unit tests are done.
    dependsOn:
      - UnitMac
    pool: server # not a real job, so doesn't need an agent
  - job: MergeCoverage
    variables:
      coverageName: Combined
    dependsOn:
      - AllUnitTests
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: etc/azureTemplate/downloadCoverage.yml
        parameters:
          inputName: OpenJdk10Mac
      - template: etc/azureTemplate/downloadCoverage.yml
        parameters:
          inputName: OpenJdk11Mac
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(System.ArtifactsDirectory)
          targetFolder: target
      - script: ./aggregate.sh
        displayName: Merge Coverage Reports
      - script: ls -R
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'JaCoCo' # Options: cobertura, jaCoCo
          summaryFileLocation: target/site/jacoco-aggregate/jacoco.xml
          reportDirectory: target
          failIfCoverageEmpty: true
