variables:
- group: Build Secrets
- name: zuluLinux07
  value: '/usr/lib/jvm/zulu-7-azure-amd64'
- name: zuluLinux08
  value: '/usr/lib/jvm/zulu-8-azure-amd64'
- name: zuluLinuxLatest
  value: '/usr/lib/jvm/zulu-12-azure-amd64' # JDK 13 isn't preinstalled as of 2019-09-18
- name: openjnine11linux
  value: 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'
- name: openJNineLatestLinux
  value: 'https://api.adoptopenjdk.net/v3/binary/latest/13/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'
trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - 'dependabot/*'
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - .github/
      - docs/
      - 'benchmark/*.iml'
      - 'betterrandom/*.iml'
      - 'FifoFiller/*.iml'
schedules:
  - cron: "23 0 * * *"
    displayName: Nightly
    branches:
      include:
        - master
        - java7
pr:
  branches:
    include:
      - master
      - java7
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - .github/
      - docs/
      - 'benchmark/*.iml'
      - 'betterrandom/*.iml'
      - 'FifoFiller/*.iml'
stages:
  - stage: UnitTests
    jobs:
    - job: UnitTest
      variables:
        JAVA_HOME: $(zuluLinux07)
        artifactEnvName: OpenJdk07Linux
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: etc/azureTemplate/installHaveged.yml
      - script: ./etc/scripts/unit-tests.sh
        displayName: Build & Test
        env:
          JAVA_HOME: $(zuluLinux07)
          JAVA_HOME_7_X64: $(zuluLinux07)
          RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
      - template: etc/azureTemplate/publishCoverage.yml
  - stage: Mutation
    dependsOn:
      - UnitTests
    jobs:
    - job: Mutation
      timeoutInMinutes: 90
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/installHaveged.yml
        - script: ./etc/scripts/mutation.sh
          displayName: Build & Run Mutation Tests
          env:
            RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
            JAVA_HOME: $(zuluLinux08)
        - task: PublishBuildArtifacts@1
          displayName: Publish Mutation Report
          inputs:
            pathtoPublish: betterrandom/target/pit-reports
            artifactName: Mutation Coverage
  - stage: Benchmark
    dependsOn:
      - UnitTests
    jobs:
    - job: Benchmark
      timeoutInMinutes: 80
      variables:
        JAVA_HOME: $(zuluLinux07)
        artifactEnvName: 'OpenJDK07Linux'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/benchmark.yml
