variables:
- group: Secrets
- name: zuluLinux07
  value: '/usr/lib/jvm/zulu-7-azure-amd64'
- name: zuluLinuxLatest #https://github.com/Microsoft/azure-pipelines-image-generation/commit/4afff89de2e3ff3ca34a445c20c7ef9e3ce306b1#commitcomment-33056031
  value: '/usr/lib/jvm/zulu-11-azure-amd64'
trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - 'dependabot*'
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - docs/
pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - docs/
jobs:
  - job: UnitTest
    variables:
      JAVA_HOME: $(zuluLinuxLatest)
      artifactEnvName: OpenJdk07Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: ./unit-tests.sh
      displayName: Build & Test
      env:
        JAVA_HOME: $(JAVA_HOME)
        RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
    - template: etc/azureTemplate/publishTargetFolderIfFailed.yml
    - template: etc/azureTemplate/publishCoverage.yml
  - job: Mutation
    dependsOn:
      - UnitTest
    timeoutInMinutes: 120 # FIXME: Remove once reliably passing in 50
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          sudo apt install haveged
          sudo service haveged start
        displayName: Install Haveged
      - script: ./mutation.sh
        displayName: Build & Run Mutation Tests
        env:
          RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
          JAVA_HOME: $(zuluLinuxLatest)
        continueOnError: true # https://github.com/hcoles/pitest/issues/597
      - template: etc/azureTemplate/publishTargetFolderIfFailed.yml
      - task: PublishBuildArtifacts@1
        displayName: Publish Mutation Report
        inputs:
          pathtoPublish: betterrandom/target/pit-reports
          artifactName: Mutation Coverage
        continueOnError: true # https://github.com/hcoles/pitest/issues/597
  - job: Benchmark
    dependsOn:
      - UnitTest
    variables:
      JAVA_HOME: $(zuluLinux07)
      artifactEnvName: 'OpenJDK07Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: etc/azureTemplate/benchmark.yml
