trigger:
  branches:
    include:
    - master
    - java7
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
pr:
  branches:
    include:
    - master
    - java7
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
resources:
  containers:
  - container: linux # reusable alias
    image: ubuntu:16.04
jobs:
- job: UnitOSX
  strategy:
    matrix:
      Java08:
        javaVersion: '8'
      Java09:
        javaVersion: '9'
      Java10:
        javaVersion: '10'
      Java11:
        javaVersion: '11'
      Java12:
        javaVersion: '12'
  pool:
    vmImage: 'macOs-10.13'
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: $(javaVersion)
      jdkArchitectureOption: x64
      jdkSourceOption: azureStorage
      jdkDestinationDirectory: jdk
  - script: unit-tests.sh
