trigger:
  branches:
    include:
    - master
    - java7
    - azurePipeline
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
pr:
  branches:
    include:
    - master
    - java7
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
jobs:
- job: UnitOSX
  pool:
    vmImage: 'macOs-10.13'
  steps:
  - script: ./unit-tests.sh
- job: UnitLinux
  strategy:
    matrix:
      OracleJdk08:
        javaInstall: 'sudo add-apt-repository ppa:webupd8team/java && sudo apt-get update && sudo apt-get install oracle-java8-installer' 
#      OracleJdk09:
#        javaInstall: 'sudo add-apt-repository ppa:webupd8team/java && sudo apt-get update && sudo apt-get install oracle-java9-installer' 
      OracleJdk10:
        javaInstall: 'sudo add-apt-repository ppa:linuxuprising/java && sudo apt-get update && sudo apt-get install oracle-java10-installer'
      OracleJdk11:
        javaInstall: 'sudo add-apt-repository ppa:linuxuprising/java && sudo apt-get update && sudo apt-get install oracle-java11-installer'
      OpenJdk08:
        javaInstall: 'sudo apt-get install openjdk-8-jdk'
      OpenJdk09:
        javaInstall: 'sudo apt-get -o Dpkg::Options::="--force-overwrite" install openjdk-9-jdk'
      OpenJdk11:
        javaInstall: 'sudo apt-get update && sudo apt dist-upgrade && sudo apt-get install openjdk-11-jdk'
      OpenJdk12:
        javaInstall: 'sudo add-apt-package "deb http://http.us.debian.org/debian unstable main non-free contrib" && sudo apt-get update && sudo apt-get install openjdk-12-jdk'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # Pre-accept licences
  - script: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - script: echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  - script: $(javaInstall)
  - script: ./unit-tests.sh
- job: UnitWindows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: ./unit-tests.ps1
