variables:
  openjdk11linux: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_9.tar.gz' 
  openjdk10linux: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2%2B13.tar.gz'
  openjdk09linux: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_linux_hotspot_9.0.4_11.tar.gz'
  openjdk08linux: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz'
  openjdk11mac: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_mac_hotspot_11.0.2_9.tar.gz'
  openjdk10mac: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Mac_jdk-10.0.2%2B13.tar.gz'
  openjdk09mac: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_mac_hotspot_9_181.tar.gz'
  openjdk08mac: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u202b08.tar.gz'
  openjdk11win: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.2_9.zip'
  openjdk10win: 'https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Win_jdk-10.0.2%2B13.zip'
  openjdk09win: 'https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9.0.4%2B11/OpenJDK9U-jdk_x64_windows_hotspot_9.0.4_11.zip'
  openjdk08win: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u202b08.zip'
  openjnine11linux: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz'
  openjnine11mac: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_mac_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz'
  openjnine11win: 'https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_windows_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.zip'
#  openjnine10linux: 'https://github.com/AdoptOpenJDK/openjdk10-openj9-releases/releases/download/jdk-10.0.2%2B13_openj9-0.9.0/OpenJDK10-OPENJ9_x64_Linux_jdk-10.0.2.13_openj9-0.9.0.tar.gz'
#  openjnine09linux: 'https://github.com/AdoptOpenJDK/openjdk9-openj9-releases/releases/download/jdk-9.0.4%2B12_openj9-0.9.0/OpenJDK9-OPENJ9_x64_Linux_jdk-9.0.4.12_openj9-0.9.0.tar.gz'
trigger:
  branches:
    include:
#    - master
#    - java7
    - azurePipeline201903
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
#pr:
#  branches:
#    include:
#    - master
#    - java7
#  paths:
#    exclude:
#    - README.md
#    - CHANGELOG.md
jobs:
- job: UnitOracle
  strategy:
    matrix:
#      OracleJdk08:
#        JAVA8: 'true'
#        javaLicence: BCL
#        javaVersion: '8'
#      OracleJdk08_LimitedCrypto:
#        JAVA8: 'true'
#        LIMITED_CRYPTO: 'true'
#        javaLicence: BCL
#        javaVersion: '8'
      OracleJdk11Linux:
        javaLicence: BCL
        javaVersion: '11'
        installJdkOs: 'linux-x64'
        vmImage: 'ubuntu-16.04'
        inputName: OracleJdk11Linux
      OracleJdk11Mac:
        javaLicence: BCL
        javaVersion: '11'
        installJdkOs: 'osx-x64'
        vmImage: 'macOs-10.13'        
        inputName: OracleJdk11Mac
  pool:
    vmImage: $(vmImage)
  steps:
  - template: azureTemplate/downloadJava.yml
  - script: ./unit-tests.sh
    displayName: Build & Test
  - template: azureTemplate/publishCoverage.yml
- job: UnitMac
  variables:
    JAVA_HOME: jdk
  strategy:
    matrix:
      # Java 7 is /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
      OpenJdk08Mac:
        JAVA8: 'true'
        JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home'
        inputName: OpenJdk08Mac
      OpenJdk09Mac:
        JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home'
        inputName: OpenJdk09Mac
      OpenJdk10Mac:
        JAVA_HOME: '/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home'
        inputName: OpenJdk10Mac
      OpenJdk11Mac:
        JAVA_HOME: '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'
        inputName: OpenJdk11Mac
  pool:
    vmImage: 'macOs-10.13'
  steps:
  - script: ./unit-tests.sh
    displayName: Build & Test
  - template: azureTemplate/publishCoverage.yml
- job: UnitLinux
  variables:
    JAVA_HOME: jdk
  strategy:
    matrix:
      OpenJdk08Linux:
        JAVA8: 'true'
        javaUrl: $(OpenJdk08Linux)
        vmImage: 'ubuntu-16.04'
        inputName: LinuxOpenJDK8
      OpenJdk09Linux:
        javaUrl: $(OpenJdk09Linux)
        vmImage: 'ubuntu-16.04'
        inputName: LinuxOpenJDK9
      OpenJdk10Linux:
        javaUrl: $(OpenJdk10Linux)
        vmImage: 'ubuntu-16.04'
        inputName: LinuxOpenJDK10
      OpenJdk11Linux:
        javaUrl: $(OpenJdk11Linux)
        vmImage: 'ubuntu-16.04'
        inputName: LinuxOpenJDK11
      OpenJNine11Linux:
        javaUrl: $(OpenJNine11Linux)
        vmImage: 'ubuntu-16.04'
        inputName: LinuxOpenJNine11
#      OpenJNine11Mac:
#        javaUrl: $(openjnine11mac)
#        vmImage: 'macOs-10.13'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: wget $(javaUrl) -O jdk.tar.gz
    displayName: Download Java
  - task: JavaToolInstaller@0
    displayName: Install Java
    inputs:
      jdkSourceOption: localDirectory
      jdkFile: jdk.tar.gz
      cleanDestinationDirectory: true 
      jdkDestinationDirectory: $(JAVA_HOME)
      jdkArchitectureOption: x64
  - script: ./unit-tests.sh
    displayName: Build & Test
  - template: azureTemplate/publishCoverage.yml
- job: UnitWindows
  variables:
    inputName: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: ./unit-tests.ps1
  - template: azureTemplate/publishCoverage.yml      
- job: MergeCoverage
  variables:
    inputName: Combined
  dependsOn:
  - UnitWindows
  - UnitMac
  - UnitLinux
  - UnitOracle
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OracleJdk11Linux
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OracleJdk11Mac
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk08Mac
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk09Mac
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk10Mac
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk11Mac
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk08Linux
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk09Linux
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk10Linux
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJdk11Linux
  - template: azureTemplate/downloadCoverage.yml
    parameters:
      inputName: OpenJNine11Linux
  - bash: mkdir target
  - bash: mv $(System.ArtifactsDirectory)/*.exec target
  - bash: mv travis-resources/jacoco_merge.yml ./pom.xml
  - bash: mvn "jacoco:report-aggregate"
  - task: PublishCodeCoverageResults@1
    inputs:
      #codeCoverageTool: 'JaCoCo' # Options: cobertura, jaCoCo
      summaryFileLocation: target/jacoco.exec
      additionalCodeCoverageFiles: target/**/*.exec
      failIfCoverageEmpty: true
