trigger:
  branches:
    include:
    - master
    - java7
    - azurePipeline
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
pr:
  branches:
    include:
    - master
    - java7
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
jobs:
- job: UnitOSX
  pool:
    vmImage: 'macOs-10.13'
  steps:
  - script: unit-tests.sh
- job: UnitLinux
  strategy:
    matrix:
      OracleJdk08:
        javaInstall: 'sudo add-apt-repository ppa:webupd8team/java && sudo apt-get update && sudo apt-get install oracle-java8-installer' 
      OracleJdk09:
        javaInstall: 'sudo add-apt-repository ppa:webupd8team/java && sudo apt-get update && sudo apt-get install oracle-java9-installer' 
      OracleJdk10:
        javaInstall: 'sudo add-apt-repository ppa:linuxuprising/java && sudo apt-get update && sudo apt-get install oracle-java10-installer'
      OracleJdk11:
        javaInstall: 'sudo add-apt-repository ppa:linuxuprising/java && sudo apt-get update && sudo apt-get install oracle-java11-installer'
      OpenJdk08:
        javaInstall: 'sudo apt-get install openjdk-8-jdk'
      OpenJdk09:
        javaInstall: 'sudo apt-get install openjdk-9-jdk'
      OpenJdk11:
        javaInstall: 'sudo apt-get install openjdk-11-jdk'
      OpenJdk12:
        javaVersion: 'sudo apt-get install openjdk-12-jdk'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: $(javaVersion)
      jdkArchitectureOption: x64
      jdkSourceOption: azureStorage
      jdkDestinationDirectory: jdk
  - script: unit-tests.sh
- job: UnitWindows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: unit-tests.ps1
